# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PanePatrol < Formula
  desc "ZFC-compliant terminal pane monitor for AI coding agents"
  homepage "https://github.com/timvw/pane-patrol"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.1.0/pane-patrol_0.1.0_darwin_amd64.tar.gz"
      sha256 "bd83f8b6302cacb93a2717dbc8a8471380a1953aa4715a43502fd3e7922b463d"

      def install
        bin.install "pane-patrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.1.0/pane-patrol_0.1.0_darwin_arm64.tar.gz"
      sha256 "dfd034d97132cbb82da2d3316857e0eeeddf99225f025815ee2c5f886ccf1917"

      def install
        bin.install "pane-patrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.1.0/pane-patrol_0.1.0_linux_amd64.tar.gz"
      sha256 "7298b2d0c10756a30849c46ea8b0f67864c42cbb185ed24bdae7bfee5209626e"
      def install
        bin.install "pane-patrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.1.0/pane-patrol_0.1.0_linux_arm64.tar.gz"
      sha256 "9da130f40a6a3d07dd31fd79639c1cafccad499c4d3d9fab994939c932a2c10f"
      def install
        bin.install "pane-patrol"
      end
    end
  end

  test do
    assert_match "pane-patrol version", shell_output("#{bin}/pane-patrol version")
  end
end
