# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PanePatrol < Formula
  desc "ZFC-compliant terminal pane monitor for AI coding agents"
  homepage "https://github.com/timvw/pane-patrol"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.3.0/pane-patrol_0.3.0_darwin_amd64.tar.gz"
      sha256 "1fa75e48bc3ec649471d8c792df330c292f598262f52f922c8e62c6679dc0acb"

      def install
        bin.install "pane-patrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.3.0/pane-patrol_0.3.0_darwin_arm64.tar.gz"
      sha256 "d5ee3f46933786b6466e835ce43aee74f542efc1a4dc8bfd2abe6c2924a5ad8e"

      def install
        bin.install "pane-patrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.3.0/pane-patrol_0.3.0_linux_amd64.tar.gz"
      sha256 "172dc03eadeef674429c6ef585c9c430a86a9df8f91226b69dd2ed3ab8de237a"
      def install
        bin.install "pane-patrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/pane-patrol/releases/download/v0.3.0/pane-patrol_0.3.0_linux_arm64.tar.gz"
      sha256 "01a4d6fa9f663e536066e5268f8b5e8f844ffb8ebfbd9fb23e4b8fdf3d0021b2"
      def install
        bin.install "pane-patrol"
      end
    end
  end

  test do
    assert_match "pane-patrol version", shell_output("#{bin}/pane-patrol version")
  end
end
