# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Fast, simple Git worktree helper"
  homepage "https://github.com/timvw/wt"
  version "0.1.26"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timvw/wt/releases/download/v0.1.26/wt_0.1.26_darwin_amd64.tar.gz"
      sha256 "503e8d5c6b98032cc5dee0c170844aa7227b9ab90a95a31ca3f85ba25e0ba202"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timvw/wt/releases/download/v0.1.26/wt_0.1.26_darwin_arm64.tar.gz"
      sha256 "f4e69c85678cda51c40fa9ce7bafb5495bb1a35c90616124318a1636ef9531ea"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/wt/releases/download/v0.1.26/wt_0.1.26_linux_amd64.tar.gz"
      sha256 "18863a064f3d4bf9727ae96f98d2e8a12f952bda4ea480bfcc0788b04a61491e"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/wt/releases/download/v0.1.26/wt_0.1.26_linux_arm64.tar.gz"
      sha256 "4e22d2eaae31942dcc5c8b37a03dc460a1f670572c0a0588cdeddec44df1079e"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (auto-cd after checkout/create), run:
        wt init

      Then restart your shell or run:
        source ~/.zshrc    # for zsh
        source ~/.bashrc   # for bash

      To remove shell integration later:
        wt init --uninstall
    EOS
  end

  test do
    assert_match "wt version", shell_output("#{bin}/wt version")
  end
end
