# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "A fast, simple Git worktree helper"
  homepage "https://github.com/timvw/wt"
  version "0.1.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timvw/wt/releases/download/v0.1.16/wt_0.1.16_darwin_amd64.tar.gz"
      sha256 "ba21578e14c70aa7676f7b117a7fa31aad666677fe0128db6e70e289b5743bab"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timvw/wt/releases/download/v0.1.16/wt_0.1.16_darwin_arm64.tar.gz"
      sha256 "eaae5e145a4bb0aa750070302d24364ca51f6dbf5e4faed2c6e53830b0f2a6b5"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/wt/releases/download/v0.1.16/wt_0.1.16_linux_amd64.tar.gz"
      sha256 "e3f76288d51996f186b7242c92882693285fae871b1843f6b5e8311d857ea313"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/wt/releases/download/v0.1.16/wt_0.1.16_linux_arm64.tar.gz"
      sha256 "73ef7db1a557d372f5050aefbc6752bb9c2abe4e26ef3dae118e2c5c2e9dc0b2"
      def install
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (auto-cd after checkout/create), run:
        wt init

      Then restart your shell or run:
        source ~/.zshrc    # for zsh
        source ~/.bashrc   # for bash

      To remove shell integration later:
        wt init --uninstall
    EOS
  end

  test do
    assert_match "wt version", shell_output("#{bin}/wt version")
  end
end
