# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "A fast, simple Git worktree helper"
  homepage "https://github.com/timvw/wt"
  version "0.1.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timvw/wt/releases/download/v0.1.23/wt_0.1.23_darwin_amd64.tar.gz"
      sha256 "3d5b87a6719745244260ae06332ec91cd283920103e17e7415b6cbc9f08eeb85"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timvw/wt/releases/download/v0.1.23/wt_0.1.23_darwin_arm64.tar.gz"
      sha256 "58cb2cb5fbd40aee68dc11a823c4ef4b57376acf53e4dafe8a0172fea6b4213d"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/wt/releases/download/v0.1.23/wt_0.1.23_linux_amd64.tar.gz"
      sha256 "435fcec7d09c5cfcec0e19bdc083abd5e5d0a90363241246d559e19b3c3b83d4"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timvw/wt/releases/download/v0.1.23/wt_0.1.23_linux_arm64.tar.gz"
      sha256 "0ffcc254473b7602f5245d8160551950ac253f4f24e94b43b25af2a8412b1246"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (auto-cd after checkout/create), run:
        wt init

      Then restart your shell or run:
        source ~/.zshrc    # for zsh
        source ~/.bashrc   # for bash

      To remove shell integration later:
        wt init --uninstall
    EOS
  end

  test do
    assert_match "wt version", shell_output("#{bin}/wt version")
  end
end
